### PR TITLE
Adding hash methods

### PR DESCRIPTION
**Pull request by richardstrnad**
I implemented the required `__hash__` methods, there are more Classes with `__eq__` but i think these don't require hashing. But i will double check that.

Python3 passes now all offline tests.
But there is still a issue with the websocket of the Subscriber class, there is a segmentation error on the `self._ws.close()` call.

I also swapped the `assertEquals` with `assertEqual`, these are synonyms, but python3 generates a deprecated warning for [`assertEquals`](https://docs.python.org/3.5/library/unittest.html#deprecated-aliases)

---
Related:
#230 #233

### CODE REVIEW

**Comment by michsmit99** [comment]
Hi Richy,
It looks like 2 of the tests are failing in the Shippable run.
======================================================================
FAIL: test_hashing_based_on_eq_multiple_objects (__main__.TestBaseRelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/acitoolkit_test.py", line 196, in test_hashing_based_on_eq_multiple_objects
    self.assertEqual(len(test_dic), 2)
AssertionError: 3 != 2

======================================================================
FAIL: test_hashing_based_on_eq_same_object (__main__.TestBaseRelation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/acitoolkit_test.py", line 177, in test_hashing_based_on_eq_same_object
    self.assertEqual(len(test_dic), 1)
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 224 tests in 0.378s

FAILED (failures=2)

**Comment by richardstrnad** [comment]
Hi Michael,

I saw that, but currently don't understand what's the difference between '2.7' and 'pypy' in Shippable. The tests pass on '2.7' , same as the local tests with python2.7.
Will try to figure it out during the weekend :-)

Cheers
Richy

**Comment by richardstrnad** [comment]
For the pypy test to pass i had to change the `__hash__` method from using attrgetter to call the attributes explicit. Otherwise the hash was different for same attributes retrieved through attrgetter.

I had also an error on the 'test_create_pc' test with pypy, this was due to a sorting issue inside of the dictionary. Comparing the dictionary should be a valid solution.

**Comment by michsmit99** [comment]
Merged manually due to branch conflicts (commit https://github.com/datacenter/acitoolkit/commit/5e3c827d39ab35fb00ddaeb378a77d3f1ef78bbe)

**Pull request closed without merging**
